### ISSUE TITLE
4. Marzo 2016. Convocatoria: I OpenDatathon ETSINF UPV sobre uso de datos abiertos

### ISSUE THREAD

**Issue by anfersa** [OKFN-Spain/agenda#1]
Convocatoria: I OpenDatathon ETSINF UPV sobre uso de datos abiertos

·         Los participantes tendrán tres semanas para crear un proyecto basado en datos abiertos, ya sea una visualización o una aplicación web. Los proyectos finalistas serán presentados el 4 de marzo en ETSINF UPV.

Se abre el plazo para presentar propuestas al primer OpenDatathon ETSINF –UPV  organizado por MUGI, el Máster en Gestión de la Información de la ETSINF UPV-,   l’Escola Tècnica Superior d’Enginyeria Informàtica de la UPV y el Grupo DataUPV con el fin de promocionar, promover y divulgar el uso de datos abiertos, especialmente entre los miembros de la comunidad universitaria.

La iniciativa cuenta con el apoyo de la Conselleria de Transparència, Responsabilitat Social, Participació i Cooperació de la Generalitat Valenciana, Fundación Inndea, Cátedra Ciudad de Valencia de la UPV y las empresas BigML y everis. El plazo de presentación de proyectos estará abierto hasta el próximo 29 de febrero de 2016.

El I OpenDatathon cuenta con 3 categorías: mejor historia sobre los datos, mejor herramienta de exploración de datos y mejor aplicación basada en predicción de datos. También habrá una categoría especial “Premio Cátedra Ciudad de Valencia UPV” con retos que usen datos abiertos del portal del ayuntamiento de Valencia sobre rutas, salud o movilidad.

En este enlace puedes consultar el detalle de las bases para participar

Esta competición, centrada en el uso de datos abiertos, se dirige especialmente a estudiantes de la Comunidad Valenciana matriculados en el curso 2015-2016, aunque cualquier persona interesada puede participar también en la categoría 3: “Mejor aplicación basada en predicción de datos”. Cada proyecto puede formar parte de más de una categoría y quedarán excluidas aquellas propuestas que hayan sido premiadas previamente.

La organización ha preparado un listado de recursos, fuentes de datos, herramientas y ejemplos que faciliten la participación de los estudiantes en la competición.

Todos los proyectos finalistas recibirán un diploma acreditativo. Adicionalmente por cada reto se prevé un primer premio de 350 euros y un segundo premio de 150 euros.

Una vez recibidas las propuestas se seleccionarán 5 finalistas por categoría que tendrán la oportunidad de exponer sus trabajos el 4 de marzo en la ETSINF, fecha próxima a la celebración mundial del Open Data Day.

Cartel I OpenDatathon
Hahstag: #OpenDatathon 

Etiquetas: OpenData, datos abiertos, visualización, infografías, aplicaciones, app.

**Comment by flowsta** [comment]
Hecho

La próxima vez, podíais poner las URLs :)

Por cierto, habéis apuntado el evento en opendataday.org? http://github.com/okfn/opendataday.org/

**Comment by anfersa** [comment]
Perfecto, gracias. Era la primera vez y no tenía mucha idea :-(
Un cordial saludo

> El 11/2/2016, a las 17:32, Adolflow notifications@github.com escribió:
> 
> Hecho
> 
> La próxima vez, podíais poner las URLs :)
> 
> Por cierto, habéis apuntado el evento en opendataday.org? http://github.com/okfn/opendataday.org/ https://github.com/okfn/opendataday.org/
> —
> Reply to this email directly or view it on GitHub https://github.com/OKFN-Spain/agenda/issues/1#issuecomment-182945340.

---

Antonia Ferrer Sapena
Directora académica Master   en Gestión de la información (MUGI)
http://mugi.webs.upv.es
Escuela Técnica Superior de  Informática (ETSINF)
Universitat Politècnica de València
anfersa@upv.es
